main:
- name: Introduction
  url: /why-htwoo
  weight: 90
- name: About hTWOo
  url: /readme,
  weight: 100
- name: Sponsors
  url: /sponsors,
  weight: 110
- name: Guidelines
  url: '/guidelines'
  weight: 120
  params:
    dynamic: true
    blank: false
- name: How To's
  url: '/how-to'
  weight: 130
  params:
    dynamic: true
    blank: false
- name: Code of Conduct
  url: /code-of-conduct
  weight: 140
  params:
    blank: false
- name: License
  url: /licenses
  weight: 150
  params:
    blank: false

footer:
- name: "Footer Nav 1"
  url: https://n8d.at
  target: '_blank'
  params:
    blank: true
- name: "Footer Nav 2"
  url: https://n8d.at
  target: '_blank'
  params:
    blank: true
- name: "Footer Nav 3"
  url: https://n8d.at
  target: '_blank'
  params:
    blank: true
legal:
  - name: "Imprint"
    url: /imprint
    params:
      blank: false
  - name: "About"
    url: https://n8d.at
    params:
      blank: false
  - name: "Contact"
    url: https://n8d.at
    params:
      blank: true